fix `wcat` to handle not-found case

diff --git a/s/which-helpers/wcat b/s/which-helpers/wcat
--- a/s/which-helpers/wcat
+++ b/s/which-helpers/wcat
@@ -1,3 +1,8 @@
 #!/bin/sh
 
-cat $(which $@)
+w=$(which $@)
+if [ $? -ne 0 ]; then
+  echo "Not found"
+  exit 1
+fi
+cat "$w"
