move git-newcd to git-cd

diff --git a/s/git/git-copy-diffs b/s/git/git-copy-diffs
--- a/s/git/git-copy-diffs
+++ b/s/git/git-copy-diffs
@@ -1,87 +1,97 @@
-#!/bin/sh
+#!/usr/bin/python
 
-found_remote=
-found_multiple_remotes=
-for remote in devbox rpi; do
-  if git remote | grep -q $remote; then
-    if [ ! -z $found_remote ]; then
-      echo "found another eligible remote: $remote"
-      found_multiple_remotes=1
-    else
-      echo "found remote: $remote"
-      found_remote=$remote
-    fi
-  fi
-done
+import errno
+import os
+import re
+import shutil
+import subprocess
+import sys
+import tarfile
+from tempfile import mkdtemp, NamedTemporaryFile
 
-if [ ! -z $found_multiple_remotes ]; then
-  echo 'Found multiple eligible remotes'
-  exit 1
-fi
+remote=None
 
-remote=$found_remote
+push_remote_re = '(?P<name>[^\s]+)\s+((?P<user>[^@]+)@)?(?P<host>[^:]+):(?P<path>[^\s]+)\s\\(push\\)'
 
-echo "Pushing to $remote.."
-git push $remote
-echo "Pushed!"
-
-staged_diff_file=$(tmpfile)
-unstaged_diff_file=$(tmpfile)
-
-git diff --cached > $staged_diff_file
-git diff > $unstaged_diff_file
-
-echo "staged diff:"
-head "$staged_diff_file"
-echo ''
-
-echo "Unstaged diff:"
-head "$unstaged_diff_file"
-echo ''
+def git_remotes():
+  remote_lines = subprocess.Popen(['git', 'remote', '-v'], stdout=subprocess.PIPE).communicate()[0].split('\n')
+  remotes = {}
+  map(
+    lambda remote: remotes.update({remote.group('name'): remote}), 
+    filter(lambda x: x, map(lambda line: re.match(push_remote_re, line), remote_lines))
+  )
+  return remotes
 
 
-remote_host="dev-$USER"
+remote_names = [ sys.argv[1] ] if len(sys.argv) > 1 else [ 'devbox', 'rpi' ]
 
-if [ ! -z "$REMOTE_STAGED_DIFF_FILE" ]; then
-  dest_staged_diff_file="$REMOTE_STAGED_DIFF_FILE"
-else
-  dest_staged_diff_file="~/dc"
-fi
+remotes = git_remotes()
+found_remotes = [ remotes[remote] for remote in remote_names if remote in remotes ]
+if len(found_remotes) > 1:
+  raise Exception('Found multiple eligible remotes: %s' % ','.join(map(lambda remote: remote.group('name'), found_remotes)))
+if not found_remotes:
+  raise Exception('Found no eligible remotes: %s' % ','.join(remote_names))
 
-if [ ! -z "$REMOTE_UNSTAGED_DIFF_FILE" ]; then
-  dest_unstaged_diff_file="$REMOTE_UNSTAGED_DIFF_FILE"
-else
-  dest_unstaged_diff_file="~/d"
-fi
+remote = found_remotes[0]
 
-dest_staged_diff_path="$remote_host:$dest_staged_diff_file"
-dest_unstaged_diff_path="$remote_host:$dest_unstaged_diff_file"
+print "Got remote %s at host %s. Pushing.." % (remote.group('name'), remote.group('host'))
+subprocess.call([ 'git', 'push', remote.group('name') ])
+print 'Pushed!'
 
-ssh $remote_host "[[ -s $dest_staged_diff_file ]]"
-if [ $? -eq 0 ]; then
-  echo "ERROR: staged diff file already exists: $dest_staged_diff_path"
-  exit 1
-fi
+try:
+  tempdir = mkdtemp()
 
-ssh $remote_host "[[ -s $dest_unstaged_diff_file ]]"
-if [ $? -eq 0 ]; then
-  echo "ERROR: unstaged diff file already exists: $dest_unstaged_diff_path"
-  exit 1
-fi
+  unstaged_diff_file_basename = 'unstaged_diff_file'
+  staged_diff_file_basename = 'staged_diff_file'
 
-if [ -s "$staged_diff_file" ]; then
-  echo "Copying staged diff file $staged_diff_file to $dest_staged_diff_path"
-  scp $staged_diff_file $dest_staged_diff_path
-fi
+  unstaged_diff_file_path = os.path.join(tempdir, unstaged_diff_file_basename)
+  staged_diff_file_path = os.path.join(tempdir, staged_diff_file_basename)
 
-if [ -s "$unstaged_diff_file" ]; then
-  echo "Copying unstaged diff file $unstaged_diff_file to $dest_unstaged_diff_path"
-  scp $unstaged_diff_file "$dest_unstaged_diff_path"
-fi
+  tar_file_path = os.path.join(tempdir, 'diffs.tar.gz')
 
-remote_dir=$(basename $(pwd))
-remote_cmd="cd $remote_dir && git reset --hard HEAD && rm -rf \$(git ls-files --other --exclude-standard) && if [ -s $dest_staged_diff_file ]; then echo 'staged'; git apply $dest_staged_diff_file; git add .; fi && if [ -s $dest_unstaged_diff_file ]; then echo 'unstaged'; git apply $dest_unstaged_diff_file; fi && rm -f $dest_unstaged_diff_file $dest_staged_diff_file"
+  with open(unstaged_diff_file_path, 'w') as unstaged_diff_file, \
+          open(staged_diff_file_path, 'w') as staged_diff_file, \
+          tarfile.open(tar_file_path, 'w:gz') as tar:
 
-echo "remoting: $remote_cmd"
-ssh $remote_host "$remote_cmd"
+    subprocess.Popen(['git', 'diff'], stdout=unstaged_diff_file).wait()
+    unstaged_diff_file.flush()
+
+    subprocess.Popen(['git', 'diff', '--cached'], stdout=staged_diff_file).wait()
+    staged_diff_file.flush()
+
+    tar.add(staged_diff_file_path, arcname=staged_diff_file_basename)
+    tar.add(unstaged_diff_file_path, arcname=unstaged_diff_file_basename)
+
+  tar_basename = os.path.basename(tar_file_path)
+
+  #  tar.flush()
+  cmd = ['scp', tar.name, '%s:%s' % (remote.group('host'), remote.group('path'))]
+  print "scp'ing tar file: %s" % ' '.join(cmd)
+  subprocess.call(cmd)
+
+  remote_cmd = ' && '.join([
+    "cd %s" % remote.group("path"),
+    "git reset --hard HEAD",
+    "if [ -e %(staged)s ]; then echo 'ERROR: staged diff file %(staged)s already exists'; exit 1; fi" % { 'staged': staged_diff_file_basename },
+    "tar mxf %s" % tar_basename,
+    "if [ -s %(staged)s ]; then echo 'applying staged diff'; git apply %(staged)s; git add .; git reset %(staged)s %(unstaged)s %(tar)s; fi" % { 'staged': staged_diff_file_basename, 'unstaged': unstaged_diff_file_basename, 'tar': tar_basename },
+    "if [ -s %(filename)s ]; then echo 'applying unstaged diff'; git apply %(filename)s; fi" % { 'filename': unstaged_diff_file_basename },
+    "rm -rf $(git ls-files --other --exclude-standard)",
+  ])
+
+  print 'remote_cmd: %s' % remote_cmd
+
+  subprocess.call([ 'ssh', remote.group('host'), remote_cmd ])
+
+finally:
+  try:
+    shutil.rmtree(tempdir)
+  except OSError as exc:  
+    if exc.errno != errno.ENOENT:  # ENOENT - no such file or directory
+      raise  # re-raise exception    
+
+
+
+
+
 
