verify mk-git commands/aliases don't already exist

diff --git a/s/git/mk-git b/s/git/mk-git
--- a/s/git/mk-git
+++ b/s/git/mk-git
@@ -9,7 +9,23 @@ cd "$s/git"
 full="git-$1"
 short="git-$2"
 
-chmd "$full"
+verify_commands_dont_exist() {
+  for arg in "$@"; do
+    if git command-exists "$arg"; then
+      err "Found existing git command: $arg"
+      exit 1
+    fi
+  done
+}
+verify_commands_dont_exist "$full" "$short"
+
+if [ ! -e "$full" ]; then
+  err "Can't find $PWD/$full"
+  exit 1
+fi
+
+chmod 755 "$full"
+
 cd "aliases"
 ln -s ../"$full" "$short"
 
